-- Generated from src/data/centers.json and src/data/config.json.
-- naverMapUrl is intentionally dropped: it's not in the documented
-- data-schema.md contract and unused by src/utils/naverMap.js.
-- Run after supabase/migrations/20260916100000_init_schema.sql.

insert into public.centers
  (id, name, address, region, description, images, is_affiliated, naver_place_id, phone, prices, affiliate_prices, sns_links, parking, i18n)
values
  ('center_01', '그래비티클라이밍 수원역점 (~06.30)', '경기도 수원시 팔달구 갓매산로 31 홍익스포츠프라자 2층', '수원', '수원역 인근에 위치한 그래비티클라이밍 센터입니다. 사장님이 에리카 선배님이셔서 파격 할인. 6월 30일까지 영업 😢', ARRAY['center_01_main.png', 'center_01_00.png', 'center_01_01.jpg', 'center_01_02.jpg', 'center_01_03.jpg', 'center_01_04.jpg'], true, '3ziNUg,2AzuBI,그래비티클라이밍%20수원역점,1774691117,PLACE_POI', '031-242-5014', $jsonb$[{"name":"일일 이용","nameEn":"Day Pass","price":20000},{"name":"암벽화 1일 대여료","nameEn":"Climbing Shoes Rental (1 day)","price":3000},{"name":"초크 1일 대여료","nameEn":"Chalk Rental (1 day)","price":2000},{"name":"주말이용권(8주)","nameEn":"Weekend Pass (8 weeks)","price":130000},{"name":"1개월","nameEn":"1-Month Pass","price":130000},{"name":"3개월","nameEn":"3-Month Pass","price":330000},{"name":"1일 체험 강습 (예약 필수)","nameEn":"Trial Lesson (Reservation Required)","price":25000}]$jsonb$::jsonb, $jsonb$[{"name":"단체 이용(10인 이상)","nameEn":"Group Entry (10+ people)","price":14000},{"name":"동아리 회원 5회권","nameEn":"Club Member 5-Visit Pass","price":70000},{"name":"동아리 회원 1개월","nameEn":"Club Member 1-Month Pass","price":100000},{"name":"동아리 회원 3개월","nameEn":"Club Member 3-Month Pass","price":250000}]$jsonb$::jsonb, $jsonb$[{"type":"instagram","url":"https://www.instagram.com/gravity_suwon_station/"}]$jsonb$::jsonb, $jsonb${"type":"self","description":"주차 1시간 30분 무료, 볼링장에서 음료수 구입시 1시간 30분 추가 무료"}$jsonb$::jsonb, $jsonb${"name":"Gravity Climbing Suwon Station (until 06.30)","address":"2F Hongik Sports Plaza, 31 Gatmaesanro, Paldal-gu, Suwon-si, Gyeonggi-do","description":"Gravity Climbing center near Suwon Station. Special discounts available as the owner is our club's senior member Erica. Closing on June 31st 😢","parking":{"description":"Free 1 hour and 30 minutes of parking, 1 hour and 30 minutes of additional free when buying drinks at the bowling alley"}}$jsonb$::jsonb),
  ('center_02', '에어즈락클라이밍 범계점', '경기도 안양시 동안구 시민대로 161 (범계역 8번 출구에서 67m)', '안양', '깔끔하고 쾌적한 암장 내부에 젤라또 아이스크림 판매', ARRAY['center_02_main.png', 'center_02_00.png', 'center_02_01.png', 'center_02_02.png', 'center_02_03.png', 'center_02_04.jpg'], true, '3zgsby,2AEF9b,에어즈락%20클라이밍%20범계점,1342684445,PLACE_POI', null, $jsonb$[{"name":"스타터패키지(1개월 자유이용권 + 7회 강습 + 암벽화 증정)","nameEn":"Starter Package (1-Month Pass + 7 Lessons + Shoes Gift)","price":250000},{"name":"일일 이용 (할인 이벤트)","nameEn":"Day Pass (Discount Event)","price":25000},{"name":"암벽화 1일 대여료","nameEn":"Climbing Shoes Rental (1 day)","price":3000},{"name":"초크 1일 대여료","nameEn":"Chalk Rental (1 day)","price":2000},{"name":"1개월 자유이용 + 7회 강습","nameEn":"1-Month Pass + 7 Lessons","price":200000},{"name":"1개월 자유이용","nameEn":"1-Month Pass","price":130000},{"name":"3개월 자유이용","nameEn":"3-Month Pass","price":330000},{"name":"6개월 자유이용","nameEn":"6-Month Pass","price":600000},{"name":"5회권","nameEn":"5-Visit Pass","price":90000},{"name":"10회권","nameEn":"10-Visit Pass","price":170000},{"name":"1일 체험 강습(40분 + 강습일 자유이용 + 암벽화 대여)","nameEn":"Trial Lesson (40min + Free Climb + Shoe Rental)","price":30000}]$jsonb$::jsonb, $jsonb$[{"name":"단체 이용(10인 이상)","nameEn":"Group Entry (10+ people)","price":15000},{"name":"동아리 회원 일일","nameEn":"Club Member Day Pass","price":20000}]$jsonb$::jsonb, $jsonb$[{"type":"instagram","url":"https://www.instagram.com/ayersrock_beomgye"},{"type":"blog","url":"https://blog.naver.com/ayersrockclimbing"}]$jsonb$::jsonb, $jsonb${"type":"self","description":"건물 내 주차 2시간 무료 (*추가 30분당 1,000원)"}$jsonb$::jsonb, $jsonb${"name":"AyersRock Climbing Beomgye Station","address":"Room 201, 2F, 161, Citizens' Boulevard, Dongan-gu, Anyang-si, Gyeonggi-do","description":"Clean and comfortable climbing gym interior with gelato ice cream for sale.","parking":{"description":"Free 2 hours of parking in the building (*KRW 1,000 per additional 30 minutes)"}}$jsonb$::jsonb),
  ('center_03', '스파이시클라이밍', '경기도 군포시 엘에스로 153-8 (금정역 1번 출구에서 382m)', '군포', '문제 퀄리티 Good, 실력 향상에 도움', ARRAY['center_03_main.png', 'center_03_00.png', 'center_03_01.jpg', 'center_03_02.jpg', 'center_03_03.jpg', 'center_03_04.jpg'], true, '3zgh3j,2ADYGc,스파이시클라이밍,2050009656,PLACE_POI', null, $jsonb$[{"name":"일일 이용","nameEn":"Day Pass","price":20000},{"name":"암벽화 1일 대여료","nameEn":"Climbing Shoes Rental (1 day)","price":3000},{"name":"초크 1일 대여료","nameEn":"Chalk Rental (1 day)","price":2000},{"name":"1일 체험 강습(30분 + 자유이용 + 암벽화 대여)","nameEn":"Trial Lesson (30min + Free Climb + Shoe Rental)","price":25000},{"name":"5회권","nameEn":"5-Visit Pass","price":90000},{"name":"10회권","nameEn":"10-Visit Pass","price":170000},{"name":"1개월","nameEn":"1-Month Pass","price":130000},{"name":"3개월","nameEn":"3-Month Pass","price":330000},{"name":"평일 주2회 4주 강습 + 1개월","nameEn":"Weekday 2x/Week Lesson (4 weeks) + 1-Month Pass","price":220000},{"name":"주말 주1회 4주 강습 + 1개월","nameEn":"Weekend 1x/Week Lesson (4 weeks) + 1-Month Pass","price":170000}]$jsonb$::jsonb, $jsonb$[{"name":"단체 이용(10인 이상)","nameEn":"Group Entry (10+ people)","price":17000},{"name":"동아리 회원 1개월","nameEn":"Club Member 1-Month Pass","price":120000}]$jsonb$::jsonb, $jsonb$[{"type":"instagram","url":"https://www.instagram.com/spicy_climbing/"}]$jsonb$::jsonb, $jsonb${"type":"self","description":"최초 3시간 무료, 4시간: 2,000원, 4시간 30분: 2,500원, 5시간: 3,000원 이후 20분당 1,000원씩 추가요금 부과, 최대 25,000원"}$jsonb$::jsonb, $jsonb${"name":"Spicy Climbing Center","address":"153-8, L-S Road, Gunpo-si, Gyeonggi-do","description":"Good quality problems that help improve your climbing skills.","parking":{"description":"Initial 3 hours free, 4 hours: 2,000 won, 4 hours 30 minutes: 2,500 won, 5 hours: 3,000 won, subsequent 20 minutes: 1,000 won each, maximum 25,000 won"}}$jsonb$::jsonb),
  ('center_04', 'KIN:D 클라이밍', '경기도 수원시 권선구 세화로 124 (수원역 3번 출구에서 578m)', '수원', '국내 최대 규모의 실내 암장, 천장이 높음, 없는거 빼고 다있음', ARRAY['center_04_main.png'], false, '3ziyEU,2Azm9k,킨디클라이밍,1254904566,PLACE_POI', null, $jsonb$[{"name":"단체할인(5인이상)-최소1시간전 예약필수","nameEn":"Group Discount (5+ people) - Reservation Required","price":20000},{"name":"단체할인(10인이상)-최소1시간전예약필수","nameEn":"Group Discount (10+ people) - Reservation Required","price":18000},{"name":"학생할인-대학생 학생증 제시","nameEn":"Student Discount - Student card Required","price":19800},{"name":"일일 이용","nameEn":"Day Pass","price":22000},{"name":"암벽화 1일 대여료","nameEn":"Climbing Shoes Rental (1 day)","price":3000},{"name":"초크 1일 대여료","nameEn":"Chalk Rental (1 day)","price":2000}]$jsonb$::jsonb, null, null, null, $jsonb${"name":"KIN:D Climbing","address":"124, Sehwa-ro, Gwonseon-gu, Suwon-si, Gyeonggi-do","description":"The largest indoor climbing gym in Korea with high ceilings and a wide variety of climbing routes."}$jsonb$::jsonb),
  ('center_05', '락클라이밍', '경기도 군포시 광정로 60 우주타운빌딩 9층 (산본역 3번 출구에서 218m)', '군포', '단체 이용 없이도 저렴한 가격, 넓은 지구력존', ARRAY['center_05_main.png'], false, '3zfGqb,2ADkst,락클라이밍%20산본,36624675,PLACE_POI', null, $jsonb$[{"name":"일일 이용","nameEn":"Day Pass","price":15000},{"name":"단체할인(10인이상)-최소1시간전 예약필수","nameEn":"Group Discount (10+ people) - Reservation Required","price":13000},{"name":"암벽화 1일 대여료","nameEn":"Climbing Shoes Rental (1 day)","price":3000}]$jsonb$::jsonb, null, null, null, $jsonb${"name":"Rock Climbing Sanbon","address":"60, Gwangjeong-ro, Gunpo-si, Gyeonggi-do, 9th floor of Uju Town Building","description":"Affordable prices even without group entry and a spacious endurance zone."}$jsonb$::jsonb),
  ('center_06', '슈퍼비클라이밍', '경기 수원시 영통구 청명남로 40 3층 (영통역 1번 출구에서 527m, 도보 5분)', '수원', '볼더링 파티 장소', ARRAY['center_06_main.jpg'], false, '3zlMRH,2AyTgv,슈퍼비클라이밍,1319993236,PLACE_POI', null, $jsonb$[{"name":"일일 이용","nameEn":"Day Pass","price":20000},{"name":"단체 이용(5인 이상)","nameEn":"Group Entry (5+ people)","price":18000},{"name":"암벽화 1일 대여료","nameEn":"Climbing Shoes Rental (1 day)","price":3000},{"name":"초크 1일 대여료","nameEn":"Chalk Rental (1 day)","price":1000}]$jsonb$::jsonb, null, $jsonb$[{"type":"instagram","url":"https://www.instagram.com/superb_yeongtong/"}]$jsonb$::jsonb, null, $jsonb${"name":"Super B Climbing","address":"3rd floor, 40 Cheongmyeongnam-ro, Yeongtong-gu, Suwon-si, Gyeonggi-do","description":"Venue for our bouldering parties."}$jsonb$::jsonb),
  ('center_07', '서울숲클라이밍 영등포점', '서울 영등포구 문래로 164 1층 (문래역 5번 출구 400m)', '서울', '서울 영등포에 있는 클라이밍 센터입니다.', ARRAY['center_07_main.png'], false, '3zennQ,2AJZyQ,서울숲클라이밍%20영등포점,1013096161,PLACE_POI', null, null, null, null, null, $jsonb${"name":"Seoul Forest Climbing Yeongdeungpo","address":"1st floor, 164 Munrae-ro, Yeongdeungpo-gu, Seoul","description":"Climbing center located in Yeongdeungpo, Seoul."}$jsonb$::jsonb),
  ('center_08', '그래비티클라이밍 영통구청점', '경기 수원시 영통구 효원로 400 탑프라자 7층(매탄권선역 4번 출구에서 968m)', '수원', 'Hy-Climb 2025년 1학기 볼더링파티 장소', ARRAY['center_08_main.png'], false, '3zkupy,2Az6AF,그래비티%20클라이밍%20영통구청점,35807313,PLACE_POI', null, $jsonb$[{"name":"일일 이용","nameEn":"Day Pass","price":20000},{"name":"암벽화 1일 대여료","nameEn":"Climbing Shoes Rental (1 day)","price":3000},{"name":"초크 1일 대여료","nameEn":"Chalk Rental (1 day)","price":2000}]$jsonb$::jsonb, null, $jsonb$[{"type":"instagram","url":"https://www.instagram.com/gravity_yeongtong/"}]$jsonb$::jsonb, null, $jsonb${"name":"Gravity Climbing Yeongtong-gu Office","address":"7th floor, Top Plaza, 400 Hyowon-ro, Yeongtong-gu, Suwon-si, Gyeonggi-do","description":"Venue for our bouldering party in the first semester of 2025."}$jsonb$::jsonb),
  ('center_09', '더클라임 사당점', '서울 관악구 과천대로 939 지층 B201호(사당역 4호선 4번출구 도보 1분거리)', '서울', '사당에 위치한 클라이밍 센터입니다.', ARRAY['center_09_main.png'], false, '3zhO9b,2AIbnA,클라이밍%20더클라임%20사당점,1542945259,PLACE_POI', null, null, null, null, null, $jsonb${"name":"The Climb Sadang","address":"B201, Basement floor, 939 Gwacheon-daero, Gwanak-gu, Seoul","description":"Climbing center located in Sadang."}$jsonb$::jsonb),
  ('center_10', '클라임투게더 수원점', '경기 수원시 영통구 덕영대로 1566 3층(망포역 1번 출구 306m)', '수원', '수원 영통에 위치한 클라이밍 센터입니다.', ARRAY['center_10_main.png'], false, '3zlbbz,2AyyXu,클라임투게더%20수원점,2074248499,PLACE_POI', null, null, null, null, null, $jsonb${"name":"Climb Together Suwon","address":"3rd floor, 1566 Deogyang-daero, Yeongtong-gu, Suwon-si, Gyeonggi-do","description":"Climbing center located in Yeongtong, Suwon."}$jsonb$::jsonb),
  ('center_11', '피크닉 클라이밍 수원점', '경기 수원시 팔달구 효원로 278 지하1층 101호', '수원', '2026년 5월에 오픈한 신규 클라이밍 센터입니다. 킨디 클라이밍과 횟수권 통합되어있습니다', ARRAY['center_11_main.png'], false, '3zjWF8,2Azeqv,피크닉클라이밍,2074634645,PLACE_POI', null, null, null, null, null, $jsonb${"name":"Picnic Climbing Suwon","address":"B1F 101, 278 Hyowon-ro, Paldal-gu, Suwon-si, Gyeonggi-do","description":"Newly opened climbing center in Suwon. Integrated with Kin:d Climbing and class packages."}$jsonb$::jsonb);

insert into public.app_config (id, departure, instagram, event, meeting)
values (
  true,
  $jsonb${"name":"한대앞역","nameEn":"HanyangUniv at Ansan Station","naverPlaceId":"3zcpZJ,2ABgcV,한대앞역2번출구,21404720,PLACE_POI"}$jsonb$::jsonb,
  'https://www.instagram.com/hyc_hy_climb/',
  $jsonb${"active":false,"title":"볼더링 파티","titleEn":"Bouldering Party","description":"5월 16일 토요일 수퍼비 클라이밍장에서\n동아리원들만을 위한 클라이밍 대회를 진행합니다!!!\n\n암장을 통째로 대여해 자유롭게 즐기는 하이클라임 대표 이벤트입니다\n대회라고 해서 부담 가질 필요 전혀 없고,\n초보자부터 실력자까지 모두 재밌게 참여할 수 있게 준비했으니\n편하게 참여해주세요😊","descriptionEn":"On Saturday, May 16\nwe will be hosting a climbing competition\nexclusively for our club members at Superbee Climbing Gym!\n\nWe’ve rented out the entire gym,\nso it’s a signature HY-Climb event\nwhere everyone can freely enjoy climbing together.\n\nEven though it’s called a “competition,”\nthere’s absolutely no pressure—\nit's designed so that everyone from beginners to advanced climbers can have fun and participate comfortably 😊","date":"2026-05-16","endDate":"2026-05-16","linkUrl":" https://hy-climb.fithub.life/center/center_06","linkLabel":"파티 장소","linkLabelEn":"Party Location"}$jsonb$::jsonb,
  $jsonb${"active":false,"centerId":"","date":"2026-05-29","time":"17:00"}$jsonb$::jsonb
);
